### PR TITLE
fix email and deprecations

### LINKED ISSUE #256: Using deprecated terraform field in provisioning
When provisioning a new cluster, here is what I get:
```
Warning: "zone": [DEPRECATED] Use location instead
  on 03_gke_cluster.tf line 42, in resource "google_container_cluster" "gke":
  42: resource "google_container_cluster" "gke" {
```

### PR DESCRIPTION
**Pull request by nicklin37**
1) Configures the user email for monitoring terraform

2) Gets rid of deprecated Zone for GKE cluster

3) Add back in the interpolation for the zone.

Closes #256 and #257

### CODE REVIEW

**Comment by nicklin37** [comment]
interpolation for the variable length of services**

File: terraform/install.sh [hunk 1]
```diff
@@ -194,14 +194,16 @@ installMonitoring() {
     return 1
   fi
 
+  acct=$(gcloud info --format="value(config.account)")
```
Comment (jiang95-dev) [inline terraform/install.sh:197]: This line should be removed.  Acct is set in getProject().

Comment (nicklin37) [reply terraform/install.sh:197]: We need to call it again to retrieve the email for the Monitoring Terraform configuration
